import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../lib/api";
import {
  Brain, Zap, FileText, GitBranch, AlertTriangle
} from "lucide-react";

type TabType = "leads" | "hidden-links";

export default function Intelligence() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<TabType>("leads");
  const [leads, setLeads] = useState<any[]>([]);
  const [hiddenLinks, setHiddenLinks] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    Promise.all([
      api.intelligenceLeads().catch(() => ({ leads: [] })),
      api.intelligenceHiddenLinks().catch(() => ({ findings: [] })),
    ]).then(([leadsRes, hiddenRes]) => {
      setLeads(leadsRes.leads || []);
      setHiddenLinks(hiddenRes.findings || []);
      setLoading(false);
    });
  }, []);

  return (
    <div className="flex flex-col h-full bg-[#020617]">
      {/* ── Top Header Strip ── */}
      <div className="px-6 py-4 border-b border-slate-800/90 space-y-3 bg-slate-900/95 backdrop-blur-md">
        {/* Module Metadata Line */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="badge badge-info text-xs font-mono tracking-wider font-bold py-0.5 px-2 bg-slate-800 text-sky-300 border border-sky-500/30">
              STATE AI INVESTIGATION INTELLIGENCE & LEADS
            </span>
            <span className="text-xs font-mono text-emerald-400 flex items-center gap-1.5 font-semibold">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
              LIVE DATABASE SYNCHRONIZED
            </span>
          </div>
          <div className="text-xs font-mono text-slate-400">
            Active Leads: <span className="text-white font-bold">{leads.length + hiddenLinks.length}</span> Algorithmic Findings
          </div>
        </div>

        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-slate-950 text-purple-400 border border-slate-800 flex items-center justify-center shadow-md">
              <Brain size={20} />
            </div>
            <div>
              <div className="flex items-center gap-2.5">
                <h1 className="text-2xl md:text-3xl font-black tracking-tight uppercase text-white">
                  AI Investigation Insights & Leads
                </h1>
                <span className="badge badge-low text-xs font-mono font-bold bg-purple-950/60 text-purple-300 border-purple-800/60">
                  ASSISTIVE ENGINE
                </span>
              </div>
              <p className="text-sm text-slate-300 font-medium">
                Algorithmic pattern recognition, syndicate broker detection, and cross-case associative hypotheses
              </p>
            </div>
          </div>

          <button
            onClick={() => navigate("/reports")}
            className="btn-primary py-2 px-4 text-xs md:text-sm flex items-center gap-1.5 font-mono font-bold shadow-md cursor-pointer"
          >
            <FileText size={15} />
            <span>Intelligence Reports</span>
          </button>
        </div>
      </div>

      {/* Mandatory Officer Verification Disclaimer */}
      <div className="px-6 py-3 bg-amber-950/20 border-b border-amber-500/30 text-xs md:text-sm text-amber-200/90 flex items-center gap-2.5">
        <AlertTriangle size={16} className="text-amber-400 shrink-0" />
        <span>
          <strong className="text-amber-300 font-bold">INVESTIGATIVE NOTICE:</strong> Suggestions generated by algorithmic models represent potential connections and require independent verification by the investigating officer.
        </span>
      </div>

      {/* Tab Navigation */}
      <div className="px-6 pt-3 border-b border-slate-800/90 bg-slate-900/95 flex gap-2">
        {(
          [
            { id: "leads", label: "Tactical Investigation Leads", count: leads.length, icon: Zap },
            { id: "hidden-links", label: "Possible Multi-Hop Links", count: hiddenLinks.length, icon: GitBranch },
          ] as const
        ).map(({ id, label, count, icon: Icon }) => (
          <button
            key={id}
            onClick={() => setActiveTab(id as TabType)}
            className={`flex items-center gap-2 px-3.5 py-2.5 text-xs md:text-sm font-mono transition-all cursor-pointer rounded-t-xl ${
              activeTab === id
                ? "bg-slate-800 text-sky-300 font-bold border-t border-x border-sky-500/40 shadow-sm"
                : "text-slate-400 hover:text-slate-200 hover:bg-slate-800/40 font-medium"
            }`}
          >
            <Icon size={14} />
            <span>{label}</span>
            <span
              className={`text-xs font-mono px-2 py-0.5 rounded-md font-bold ${
                activeTab === id ? "bg-slate-900 text-sky-300 border border-sky-500/30" : "bg-slate-950 text-slate-400"
              }`}
            >
              {count}
            </span>
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="flex-1 p-6 overflow-y-auto max-w-5xl">
        {loading ? (
          <div className="space-y-3">
            {[1, 2, 3, 4].map((i) => <div key={i} className="h-20 rounded-xl bg-slate-900/60 border border-slate-800 animate-pulse" />)}
          </div>
        ) : activeTab === "leads" ? (
          <div className="space-y-3">
            {leads.length === 0 ? (
              <div className="p-8 rounded-xl border border-slate-800/90 bg-slate-900/95 text-center text-sm text-slate-400 font-mono">
                No active tactical leads logged.
              </div>
            ) : (
              leads.map((lead, idx) => (
                <div
                  key={lead.id || idx}
                  className="p-4 rounded-xl bg-slate-900/95 border border-slate-800/90 hover:border-slate-700 transition-all shadow-xl space-y-2"
                >
                  <div className="flex items-center justify-between">
                    <span className="badge badge-low text-xs font-mono font-bold">
                      {lead.lead_type || "SUGGESTED LEAD"}
                    </span>
                    <span className="text-xs font-mono text-slate-400">
                      Confidence: <strong className="text-sky-300 font-bold">{Math.round((lead.confidence || 0.8) * 100)}%</strong>
                    </span>
                  </div>
                  <div className="text-base font-bold text-white">
                    {lead.title || lead.summary}
                  </div>
                  <p className="text-sm md:text-base text-slate-200 leading-relaxed font-normal">
                    {lead.description || lead.explanation}
                  </p>
                </div>
              ))
            )}
          </div>
        ) : (
          <div className="space-y-3">
            {hiddenLinks.length === 0 ? (
              <div className="p-8 rounded-xl border border-slate-800/90 bg-slate-900/95 text-center text-sm text-slate-400 font-mono">
                No multi-hop connections flagged at this time.
              </div>
            ) : (
              hiddenLinks.map((link, idx) => (
                <div
                  key={idx}
                  className="p-4 rounded-xl bg-slate-900/95 border border-slate-800/90 hover:border-slate-700 transition-all shadow-xl space-y-2"
                >
                  <div className="flex items-center justify-between">
                    <span className="badge badge-medium text-xs font-mono font-bold">POTENTIAL MULTI-HOP CONNECTION</span>
                    <span className="text-xs font-mono text-slate-400">
                      Hops: <strong className="text-purple-300 font-bold">{link.hops || 3}</strong>
                    </span>
                  </div>
                  <div className="text-base font-bold text-white">
                    {link.source_name} <span className="text-sky-400">↔</span> {link.target_name}
                  </div>
                  <p className="text-sm md:text-base text-slate-200 leading-relaxed font-normal">
                    {link.explanation || "Indirect linkage observed across shared telecommunication azimuths and financial conduits."}
                  </p>
                </div>
              ))
            )}
          </div>
        )}
      </div>
    </div>
  );
}
