import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../lib/api";
import {
  Brain, Zap, FileText, GitBranch, AlertTriangle
} from "lucide-react";

type TabType = "leads" | "hidden-links";

export default function Intelligence() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<TabType>("leads");
  const [leads, setLeads] = useState<any[]>([]);
  const [hiddenLinks, setHiddenLinks] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    Promise.all([
      api.intelligenceLeads().catch(() => ({ leads: [] })),
      api.intelligenceHiddenLinks().catch(() => ({ findings: [] })),
    ]).then(([leadsRes, hiddenRes]) => {
      setLeads(leadsRes.leads || []);
      setHiddenLinks(hiddenRes.findings || []);
      setLoading(false);
    });
  }, []);

  return (
    <div className="flex flex-col h-full bg-[var(--bg-void)]">
      {/* ── Top Header Strip ── */}
      <div className="px-6 py-4 border-b border-[var(--border-subtle)] flex flex-wrap items-center justify-between gap-4 bg-[var(--bg-panel-solid)]">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-zinc-800 text-zinc-100 border border-zinc-700/60 flex items-center justify-center shadow-sm">
            <Brain size={16} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-xs font-bold tracking-wide uppercase text-[var(--text-primary)]">
                AI Investigation Insights & Leads
              </h1>
              <span className="badge badge-low text-[8px]">ASSISTIVE ENGINE</span>
            </div>
            <p className="text-[11px] text-[var(--text-muted)]">
              Algorithmic pattern recognition, syndicate broker detection, and cross-case associative hypotheses
            </p>
          </div>
        </div>

        <button
          onClick={() => navigate("/reports")}
          className="btn-primary py-1.5 px-3 text-xs flex items-center gap-1.5"
        >
          <FileText size={13} />
          <span>Intelligence Reports</span>
        </button>
      </div>

      {/* Mandatory Officer Verification Disclaimer */}
      <div className="px-6 py-2.5 bg-[rgba(245,158,11,0.08)] border-b border-[rgba(245,158,11,0.2)] text-[11px] text-[var(--text-secondary)] flex items-center gap-2">
        <AlertTriangle size={13} className="text-[var(--status-warning)] shrink-0" />
        <span>
          <strong>INVESTIGATIVE NOTICE:</strong> Suggestions generated by algorithmic models represent potential connections and requires independent verification by the investigating officer.
        </span>
      </div>

      {/* Tab Navigation */}
      <div className="px-6 pt-3 border-b border-[var(--border-subtle)] bg-[var(--bg-panel)] flex gap-2">
        {(
          [
            { id: "leads", label: "Tactical Investigation Leads", count: leads.length, icon: Zap },
            { id: "hidden-links", label: "Possible Multi-Hop Links", count: hiddenLinks.length, icon: GitBranch },
          ] as const
        ).map(({ id, label, count, icon: Icon }) => (
          <button
            key={id}
            onClick={() => setActiveTab(id as TabType)}
            className={`flex items-center gap-2 px-3 py-1.5 text-xs font-medium rounded-t transition-all ${
              activeTab === id
                ? "bg-zinc-800 text-zinc-100 font-semibold border-b-2 border-zinc-100 shadow-sm"
                : "text-[var(--text-muted)] hover:text-[var(--text-secondary)]"
            }`}
          >
            <Icon size={13} />
            <span>{label}</span>
            <span
              className={`text-[9px] font-mono px-1.5 py-0.2 rounded ${
                activeTab === id ? "bg-zinc-700 text-zinc-200" : "bg-[var(--bg-panel-raised)] text-[var(--text-muted)]"
              }`}
            >
              {count}
            </span>
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="flex-1 p-6 overflow-y-auto max-w-5xl">
        {loading ? (
          <div className="space-y-3">
            {[1, 2, 3, 4].map((i) => <div key={i} className="skeleton h-20 rounded" />)}
          </div>
        ) : activeTab === "leads" ? (
          <div className="space-y-3">
            {leads.length === 0 ? (
              <div className="panel p-8 text-center text-xs text-[var(--text-muted)]">
                No active tactical leads logged.
              </div>
            ) : (
              leads.map((lead, idx) => (
                <div
                  key={lead.id || idx}
                  className="panel p-4 bg-[var(--bg-panel-solid)] hover:border-[var(--border-strong)] transition-all space-y-1.5"
                >
                  <div className="flex items-center justify-between">
                    <span className="badge badge-low text-[8px]">
                      {lead.lead_type || "SUGGESTED LEAD"}
                    </span>
                    <span className="text-[10px] font-mono text-[var(--text-muted)]">
                      Confidence of suggestion: {Math.round((lead.confidence || 0.8) * 100)}%
                    </span>
                  </div>
                  <div className="text-xs font-bold text-[var(--text-primary)]">
                    {lead.title || lead.summary}
                  </div>
                  <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                    {lead.description || lead.explanation}
                  </p>
                </div>
              ))
            )}
          </div>
        ) : (
          <div className="space-y-3">
            {hiddenLinks.length === 0 ? (
              <div className="panel p-8 text-center text-xs text-[var(--text-muted)]">
                No multi-hop connections flagged at this time.
              </div>
            ) : (
              hiddenLinks.map((link, idx) => (
                <div
                  key={idx}
                  className="panel p-4 bg-[var(--bg-panel-solid)] hover:border-[var(--border-strong)] transition-all space-y-2"
                >
                  <div className="flex items-center justify-between">
                    <span className="badge badge-medium text-[8px]">POTENTIAL MULTI-HOP CONNECTION</span>
                    <span className="text-[10px] font-mono text-[var(--text-muted)]">
                      Hops: {link.hops || 3}
                    </span>
                  </div>
                  <div className="text-xs font-bold text-[var(--text-primary)]">
                    {link.source_name} ↔ {link.target_name}
                  </div>
                  <p className="text-xs text-[var(--text-secondary)]">
                    {link.explanation || "Indirect linkage observed across shared telecommunication azimuths and financial conduits."}
                  </p>
                </div>
              ))
            )}
          </div>
        )}
      </div>
    </div>
  );
}
